### ISSUE TITLE
Documentation is insufficient

### ISSUE THREAD

**Issue by PeteK68** [MarcStan/lets-encrypt-azure#12]
Is it possible to elaborate on the steps to configure, and deploy everything? I'm encountering significant issues when trying to configure and run the solution.

Thanks,
Peter

**Comment by PeteK68** [comment]
I'm not extremely familiar with Azure DevOps, or the pipeline.yml file, so it's definitely a challenge to know what to modify and how to execute it. Any extra information would be very helpful and much appreciated.

**Comment by MarcStan** [comment]
Yes, all the documentation currently assumes some knowledge about Azure (Functions) and Azure DevOps.

I'll make a detailed blog post (possibly this weekend) and link it from here since the steps are the same pattern for all my Azure projects. This should help onboard people less familiar with all the details.

In the meantime I'll leave you with some links to the docs since they are a good starting point as well.

* [Getting started with Azure DevOps](https://docs.microsoft.com/azure/devops/get-started)
* [First pipeline](https://docs.microsoft.com/azure/devops/pipelines/create-first-pipeline)
* [Azure Functions deployment](https://docs.microsoft.com/azure/azure-functions/functions-continuous-deployment)

**Comment by MarcStan** [comment]
Hey, I put up a getting started guide for Azure DevOps + azure functions on [my blog](https://marcstan.net/blog/2019/12/07/Using-Azure-DevOps-to-deploy-Azure-functions-from-Github/) let me know if there are any remaining unclear parts.

**Comment by PeteK68** [comment]
Thanks @MarcStan, I will check it out and provide feedback, if necessary. It's appreciated.
