### ISSUE TITLE
AppServiceTargetResource aggressively tries to delete unrelated certificates

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#7]
After successfully adding an SSL certificate for `abc.mydomain.com` to an app service's resource group and binding the certificate to the app service, `AppServiceTargetResource.CleanupOldCertificatesAsync` then tried to delete two existing, unrelated certificates:

1. An **expired** certificate for `*.mydomain.com` and `mydomain.com`
1. A **valid, in-use** certificate for `www.mydomain.com` and `mydomain.com`

Fortunately, both attempts failed. The first failed because the `DELETE` call returned 400 "The request URL is invalid" error. The second failed because the `DELETE` call returned 409 "Cannot remove certificate with thumbprint _xxxx_ because it is used for hostname mydomain.com."

I can see that the function is trying to be somewhat careful about certificates it tries to delete, but in both of these cases it was too aggressive. Ideally it should only delete certificates that were issued by Let's Encrypt and would have been added by the current function configuration.

**Comment by MarcStan** [comment]
Really appreciate all the feedback!

I agree that this isn't the best user experience. Luckily Azure doesn't allow deleting resources that are in use!

Case 2 was a bug in my code (for any subdomain it would also try to delete certificates of any parent domains due to wrong matching).

I now changed it to an explicit whitelist for deletion as you suggested (based on all the old certificates in the keyvault).

Only expired certificates with exact hostname & thumbprint matches will now be removed.
